services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    security_opt:
      - no-new-privileges:true

  rabbit-mq:
    image: rabbitmq:3.10-management-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
    ports:
      - '5672:5672'   # AMQP protocol port
      - '15672:15672' # HTTP management UI
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 525M
    security_opt:
      - no-new-privileges:true

  jasmin:
    image: jookies/jasmin:latest
    restart: unless-stopped
    volumes:
      - jasmin_configs:/etc/jasmin
      - jasmin_logs:/var/log/jasmin
      - jasmin_store:/etc/jasmin/store
    ports:
      - '2775:2775'   # SMPP server port
      - '8990:8990'   # HTTP API port
      - '1401:1401'   # jCli management port
    depends_on:
      redis:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    security_opt:
      - no-new-privileges:true

volumes:
  jasmin_configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/jasmin
  jasmin_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/jasmin
  jasmin_store:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/jasmin/store
